image: alpine/edge
packages:
  - rust
  - cargo
  - faenza-icon-theme
sources:
  - https://git.sr.ht/~zethra/linicon-theme
tasks:
  - setup: |
      cd linicon-theme/test_data
      cp gtk2 ~/.gtkrc-2.0
      mkdir -p ~/.config/gtk-3.0/
      cp gtk3 ~/.config/gtk-3.0/settings.ini
      mkdir -p ~/.config/gtk-4.0/
      cp gtk4 ~/.config/gtk-4.0/settings.ini
      cp kdeglobals ~/.config/
      cp theme.conf ~/.config/
  - build: |
      cd linicon-theme
      cargo build --all-features
  - test: |
      cd linicon-theme
      export TEST_THEME=Papirus-Dark
      sudo mv ./test_data/gsettings /usr/bin/gsettings
      cargo test --all-features
